---
name: Release

on:
  pull_request:
    branches: ["main"]
    paths: ["charts/**/metadata.yaml"]
  push:
    branches: ["main"]
    paths: ["charts/**/metadata.yaml"]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@a284dc1814e3fd07f2e34267fc8f81227ed29fb8 # v45.0.9
        with:
          files: charts/**/metadata.yaml

      - name: Extract Chart values
        id: charts
        env:
          FILTER: '[.]'
        run: |
          charts=$(yq eval-all --indent=0 --output-format=json "${FILTER}" \
              ${{ steps.changed-files.outputs.all_changed_and_modified_files }} \
          )
          echo "charts=${charts}" >> $GITHUB_OUTPUT

  push-charts:
    needs: changed-files
    name: Push Charts
    runs-on: ubuntu-latest
    if: ${{ needs.changed-files.outputs.charts != '[]' }}
    strategy:
      matrix:
        charts: ${{ fromJSON(needs.changed-files.outputs.charts) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4

      - name: Install Cosign
        if: ${{ github.event_name != 'pull_request' }}
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Helm Repository
        run: helm repo add upstream ${{ matrix.charts.registry }}

      - name: Update Helm Repository
        run: helm repo update upstream

      - name: Pull Chart
        run: helm pull upstream/${{ matrix.charts.chart }} --version ${{ matrix.charts.version }}

      - name: Push Chart
        if: ${{ github.event_name != 'pull_request' }}
        run: helm push *.tgz oci://ghcr.io/${{ github.repository }}

      - name: Sign artifacts with Cosign
        if: ${{ github.event_name != 'pull_request' }}
        run: cosign sign --yes ghcr.io/${{ github.repository }}/${{ matrix.charts.chart }}:${{ matrix.charts.version }}
